[tool.dephell.main]
from = {format = "flit", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}
command = "python -m flakehell lint"

[tool.dephell.flake8]
from = {format = "pip", path = "requirements-flake.txt"}
python = ">=3.6"
command = "flake8"

[tool.dephell.pytest]
from = {format = "flit", path = "pyproject.toml"}
command = "python -m pytest tests/"

[tool.dephell.typing]
from = {format = "flit", path = "pyproject.toml"}
command = "mypy --ignore-missing-imports --allow-redefinition dephell_argparse"

# -- FLIT -- #

[tool.flit.metadata]
module="dephell_argparse"
author="Gram (@orsinium)"
author-email="master_fess@mail.ru"
home-page="https://github.com/dephell/dephell_argparse"
requires-python=">=3.5"
description-file="README.md"
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Quality Assurance",
]
